import type { Card } from '../../../shared/types';

export const MOCK_TRACKS: Card[] = [
  // 1950s
  {
    trackId: 'mock-001',
    title: 'Johnny B. Goode',
    artist: 'Chuck Berry',
    releaseYear: 1958,
    previewUrl: 'mock://track-001',
    albumArt: '',
  },
  {
    trackId: 'mock-002',
    title: 'Hound Dog',
    artist: 'Elvis Presley',
    releaseYear: 1956,
    previewUrl: 'mock://track-002',
    albumArt: '',
  },
  // 1960s
  {
    trackId: 'mock-003',
    title: 'Hey Jude',
    artist: 'The Beatles',
    releaseYear: 1968,
    previewUrl: 'mock://track-003',
    albumArt: '',
  },
  {
    trackId: 'mock-004',
    title: 'Respect',
    artist: 'Aretha Franklin',
    releaseYear: 1967,
    previewUrl: 'mock://track-004',
    albumArt: '',
  },
  {
    trackId: 'mock-005',
    title: 'Good Vibrations',
    artist: 'The Beach Boys',
    releaseYear: 1966,
    previewUrl: 'mock://track-005',
    albumArt: '',
  },
  {
    trackId: 'mock-006',
    title: 'Purple Haze',
    artist: 'Jimi Hendrix',
    releaseYear: 1967,
    previewUrl: 'mock://track-006',
    albumArt: '',
  },
  // 1970s
  {
    trackId: 'mock-007',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    releaseYear: 1975,
    previewUrl: 'mock://track-007',
    albumArt: '',
  },
  {
    trackId: 'mock-008',
    title: 'Hotel California',
    artist: 'Eagles',
    releaseYear: 1977,
    previewUrl: 'mock://track-008',
    albumArt: '',
  },
  {
    trackId: 'mock-009',
    title: 'Stayin\' Alive',
    artist: 'Bee Gees',
    releaseYear: 1977,
    previewUrl: 'mock://track-009',
    albumArt: '',
  },
  {
    trackId: 'mock-010',
    title: 'Superstition',
    artist: 'Stevie Wonder',
    releaseYear: 1972,
    previewUrl: 'mock://track-010',
    albumArt: '',
  },
  {
    trackId: 'mock-011',
    title: 'Dancing Queen',
    artist: 'ABBA',
    releaseYear: 1976,
    previewUrl: 'mock://track-011',
    albumArt: '',
  },
  {
    trackId: 'mock-012',
    title: 'Le Freak',
    artist: 'Chic',
    releaseYear: 1978,
    previewUrl: 'mock://track-012',
    albumArt: '',
  },
  // 1980s
  {
    trackId: 'mock-013',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    releaseYear: 1983,
    previewUrl: 'mock://track-013',
    albumArt: '',
  },
  {
    trackId: 'mock-014',
    title: 'Like a Prayer',
    artist: 'Madonna',
    releaseYear: 1989,
    previewUrl: 'mock://track-014',
    albumArt: '',
  },
  {
    trackId: 'mock-015',
    title: 'Sweet Child O\' Mine',
    artist: 'Guns N\' Roses',
    releaseYear: 1988,
    previewUrl: 'mock://track-015',
    albumArt: '',
  },
  {
    trackId: 'mock-016',
    title: 'Don\'t You (Forget About Me)',
    artist: 'Simple Minds',
    releaseYear: 1985,
    previewUrl: 'mock://track-016',
    albumArt: '',
  },
  {
    trackId: 'mock-017',
    title: 'Girls Just Want to Have Fun',
    artist: 'Cyndi Lauper',
    releaseYear: 1983,
    previewUrl: 'mock://track-017',
    albumArt: '',
  },
  {
    trackId: 'mock-018',
    title: 'Take On Me',
    artist: 'a-ha',
    releaseYear: 1985,
    previewUrl: 'mock://track-018',
    albumArt: '',
  },
  // 1990s
  {
    trackId: 'mock-019',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    releaseYear: 1991,
    previewUrl: 'mock://track-019',
    albumArt: '',
  },
  {
    trackId: 'mock-020',
    title: 'Baby Got Back',
    artist: 'Sir Mix-a-Lot',
    releaseYear: 1992,
    previewUrl: 'mock://track-020',
    albumArt: '',
  },
  {
    trackId: 'mock-021',
    title: 'Waterfalls',
    artist: 'TLC',
    releaseYear: 1995,
    previewUrl: 'mock://track-021',
    albumArt: '',
  },
  {
    trackId: 'mock-022',
    title: 'Wonderwall',
    artist: 'Oasis',
    releaseYear: 1995,
    previewUrl: 'mock://track-022',
    albumArt: '',
  },
  {
    trackId: 'mock-023',
    title: 'Killing Me Softly',
    artist: 'Fugees',
    releaseYear: 1996,
    previewUrl: 'mock://track-023',
    albumArt: '',
  },
  {
    trackId: 'mock-024',
    title: '...Baby One More Time',
    artist: 'Britney Spears',
    releaseYear: 1998,
    previewUrl: 'mock://track-024',
    albumArt: '',
  },
  {
    trackId: 'mock-025',
    title: 'Gangsta\'s Paradise',
    artist: 'Coolio',
    releaseYear: 1995,
    previewUrl: 'mock://track-025',
    albumArt: '',
  },
  {
    trackId: 'mock-026',
    title: 'Say My Name',
    artist: 'Destiny\'s Child',
    releaseYear: 1999,
    previewUrl: 'mock://track-026',
    albumArt: '',
  },
  // 2000s
  {
    trackId: 'mock-027',
    title: 'Crazy in Love',
    artist: 'Beyoncé ft. Jay-Z',
    releaseYear: 2003,
    previewUrl: 'mock://track-027',
    albumArt: '',
  },
  {
    trackId: 'mock-028',
    title: 'Yeah!',
    artist: 'Usher ft. Lil Jon & Ludacris',
    releaseYear: 2004,
    previewUrl: 'mock://track-028',
    albumArt: '',
  },
  {
    trackId: 'mock-029',
    title: 'Lose Yourself',
    artist: 'Eminem',
    releaseYear: 2002,
    previewUrl: 'mock://track-029',
    albumArt: '',
  },
  {
    trackId: 'mock-030',
    title: 'Rolling in the Deep',
    artist: 'Adele',
    releaseYear: 2010,
    previewUrl: 'mock://track-030',
    albumArt: '',
  },
  // 2010s
  {
    trackId: 'mock-031',
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    releaseYear: 2014,
    previewUrl: 'mock://track-031',
    albumArt: '',
  },
  {
    trackId: 'mock-032',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    releaseYear: 2017,
    previewUrl: 'mock://track-032',
    albumArt: '',
  },
  {
    trackId: 'mock-033',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    releaseYear: 2019,
    previewUrl: 'mock://track-033',
    albumArt: '',
  },
  {
    trackId: 'mock-034',
    title: 'Old Town Road',
    artist: 'Lil Nas X ft. Billy Ray Cyrus',
    releaseYear: 2019,
    previewUrl: 'mock://track-034',
    albumArt: '',
  },
  {
    trackId: 'mock-035',
    title: 'Happy',
    artist: 'Pharrell Williams',
    releaseYear: 2013,
    previewUrl: 'mock://track-035',
    albumArt: '',
  },
  {
    trackId: 'mock-036',
    title: 'Despacito',
    artist: 'Luis Fonsi ft. Daddy Yankee',
    releaseYear: 2017,
    previewUrl: 'mock://track-036',
    albumArt: '',
  },
  {
    trackId: 'mock-037',
    title: 'Bad Guy',
    artist: 'Billie Eilish',
    releaseYear: 2019,
    previewUrl: 'mock://track-037',
    albumArt: '',
  },
  // 2020s
  {
    trackId: 'mock-038',
    title: 'Levitating',
    artist: 'Dua Lipa',
    releaseYear: 2020,
    previewUrl: 'mock://track-038',
    albumArt: '',
  },
  {
    trackId: 'mock-039',
    title: 'Drivers License',
    artist: 'Olivia Rodrigo',
    releaseYear: 2021,
    previewUrl: 'mock://track-039',
    albumArt: '',
  },
  {
    trackId: 'mock-040',
    title: 'As It Was',
    artist: 'Harry Styles',
    releaseYear: 2022,
    previewUrl: 'mock://track-040',
    albumArt: '',
  },
];
